# Antibody sequence trimming
# See https://www.ncbi.nlm.nih.gov/books/NBK26884/
LIGHT_ANTIBODY_TRIM = 110
HEAVY_ANTIBODY_TRIM = 110

AB_CDRS_SEQ_LEN = 165
AB_CDRS_POS_LEN = 6
AB_FEAT_LEN = AB_CDRS_SEQ_LEN + AB_CDRS_POS_LEN

LIGHT_CDR_1_LEN = 20
LIGHT_CDR_2_LEN = 16
LIGHT_CDR_3_LEN = 36
HEAVY_CDR_1_LEN = 21
HEAVY_CDR_2_LEN = 33
HEAVY_CDR_3_LEN = 39

CDR_LENGHTS = [LIGHT_CDR_1_LEN, LIGHT_CDR_2_LEN, LIGHT_CDR_3_LEN, HEAVY_CDR_1_LEN, HEAVY_CDR_2_LEN, HEAVY_CDR_3_LEN]